//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace support_project.Context
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class cong_ty
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public cong_ty()
        {
            this.sinh_vien = new HashSet<sinh_vien>();
        }
    
        public int id_cong_ty { get; set; }
        public string ten_cong_ty { get; set; }
        public string dia_chi { get; set; }
        public string sdt { get; set; }
        public string email { get; set; }
        public string mo_ta { get; set; }
        public string anh { get; set; }
        public string chuyen_nganh { get; set; }
        [NotMapped]
        public System.Web.HttpPostedFileBase ImageUpload { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<sinh_vien> sinh_vien { get; set; }
    }
}
