//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace support_project.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class sinh_vien
    {
        public int id_sinh_vien { get; set; }
        public string ten_sinh_vien { get; set; }
        public string gioi_tinh { get; set; }
        public string ngay_sinh { get; set; }
        public string sdt { get; set; }
        public string email { get; set; }
        public string mo_ta { get; set; }
        public Nullable<int> id_cong_ty { get; set; }
        public Nullable<int> id_khoa { get; set; }
    
        public virtual cong_ty cong_ty { get; set; }
        public virtual khoa khoa { get; set; }
    }
}
